# Generated by Django 3.0.7 on 2020-06-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('sch_id', models.CharField(default='-1', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('diploma_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('grad_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('independent_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_competent_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_create_time', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_english_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('sch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_run_type', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_run_type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_type_tag_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=200)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaokao.School')),
            ],
        ),
    ]
